[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm start"
  port = 3000

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
